spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/kopidlno}
spring.datasource.username=${DB_USERNAME:kopidlno}
spring.datasource.password=${DB_PASSWORD:kopidlno}

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

app.source-url=${SOURCE_URL:https://www.smartform.cz/download/kopidlno.xml.zip}

spring.jpa.show-sql=false
logging.level.cz.kopidlno=INFO
